---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: babu11-dep
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
   #   imagePullSecrets:
    #  - name: my-registry-key
      containers:
      - name: elevendevops-container
        image: mohan7000/babu11:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
...
