---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: babu11-dep
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
   #   imagePullSecrets:
    #  - name: my-registry-key
      containers:
      - name: elevendevops-container
        image: mohan7000/babu11:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

----
apiVersion: v1
kind: Service
metadata:
 name: babu11-service
 labels:
   app: my-app
spec:
 type: NodePort
 ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30018
 selector:
   app: my-app
...
