----
apiVersion: v1
kind: Service
metadata:
 name: babu11-service
 labels:
   app: my-app
spec:
 type: NodePort
 ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30018
 selector:
   app: my-app
...
